@ECHO OFF
SETLOCAL

SET "SCRIPT_DIR=%~dp0"
PUSHD "%SCRIPT_DIR%" || EXIT /B 1
SET "PUBLISHER_JAR="
SET "INPUT_CACHE_JAR=%SCRIPT_DIR%input-cache\publisher.jar"
SET "PARENT_JAR=%SCRIPT_DIR%..\publisher.jar"

IF EXIST "%INPUT_CACHE_JAR%" SET "PUBLISHER_JAR=%INPUT_CACHE_JAR%"
IF NOT DEFINED PUBLISHER_JAR IF EXIST "%PARENT_JAR%" SET "PUBLISHER_JAR=%PARENT_JAR%"
IF NOT DEFINED PUBLISHER_JAR IF DEFINED FHIR_PUBLISHER_HOME IF EXIST "%FHIR_PUBLISHER_HOME%\publisher.jar" SET "PUBLISHER_JAR=%FHIR_PUBLISHER_HOME%\publisher.jar"
IF NOT DEFINED PUBLISHER_JAR IF DEFINED USERPROFILE IF EXIST "%USERPROFILE%\.fhir\tools\publisher\publisher.jar" SET "PUBLISHER_JAR=%USERPROFILE%\.fhir\tools\publisher\publisher.jar"

IF NOT DEFINED PUBLISHER_JAR (
    ECHO IG Publisher not found. Install it under input-cache, the parent directory, or %%USERPROFILE%%\.fhir\tools\publisher.
    POPD
    EXIT /B 1
)

SET "JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8"
SET "TX_OPTION="
SET "SUSHI_OPTION="
SET "PUBLISHER_ARGUMENTS=%*"

IF /I "%~1"=="build" SET "PUBLISHER_ARGUMENTS="
IF /I "%~1"=="notx" SET "TX_OPTION=-tx n/a"
IF /I "%~1"=="nosushi" SET "SUSHI_OPTION=-no-sushi"
IF /I "%~1"=="notx" SET "PUBLISHER_ARGUMENTS="
IF /I "%~1"=="nosushi" SET "PUBLISHER_ARGUMENTS="

IF NOT DEFINED TX_OPTION (
    PING tx.fhir.org -4 -n 1 -w 1000 >NUL 2>&1
    IF ERRORLEVEL 1 SET "TX_OPTION=-tx n/a"
)

ECHO Using IG Publisher: "%PUBLISHER_JAR%"
JAVA -jar "%PUBLISHER_JAR%" -ig . %TX_OPTION% %SUSHI_OPTION% %PUBLISHER_ARGUMENTS%
SET "BUILD_EXIT_CODE=%ERRORLEVEL%"

POPD
EXIT /B %BUILD_EXIT_CODE%
